### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by joewiz** [shabanovd/eXgit#12]
I'm getting an error when building via `mvn clean install` with a fresh checkout of the eXgit repo.  Here is the output when re-running with the `-e -X` flags to display all errors. 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.595 s
[INFO] Finished at: 2015-05-10T14:53:24-04:00
[INFO] Final Memory: 6M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project eXgit: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in http://download.eclipse.org/jgit/maven was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project eXgit: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in http://download.eclipse.org/jgit/maven was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in http://download.eclipse.org/jgit/maven was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in http://download.eclipse.org/jgit/maven was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in http://download.eclipse.org/jgit/maven was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in http://download.eclipse.org/jgit/maven was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
```

In #8 you suggested using https://github.com/eXist-db/jgit, but when I tried replacing the `jgit-repository` of `http://download.eclipse.org/jgit/maven` in the `pom.xml` with `https://raw.githubusercontent.com/eXist-db/jgit/master/`, I still got an error:

```
[ERROR] Failed to execute goal on project eXgit: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in https://raw.githubusercontent.com/eXist-db/jgit/master/ was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project eXgit: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in https://raw.githubusercontent.com/eXist-db/jgit/master/ was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in https://raw.githubusercontent.com/eXist-db/jgit/master/ was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in https://raw.githubusercontent.com/eXist-db/jgit/master/ was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in https://raw.githubusercontent.com/eXist-db/jgit/master/ was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in https://raw.githubusercontent.com/eXist-db/jgit/master/ was cached in the local repository, resolution will not be reattempted until the update interval of jgit-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
```

Do you have any suggestions for getting eXgit to build?  I'd be happy to test or submit a pull request once I get it working.

**Comment by shabanovd** [comment]
@joewiz, you need to check out https://github.com/eXist-db/jgit and deploy locally by `mvn install`

**Comment by joewiz** [comment]
Thanks for this hint.  I'm getting a test failure.  Do you get this too, or am I doing something wrong?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project org.eclipse.jgit.test: There are test failures.
```

Re-running with the `-e` flag:

```
Results :

Failed tests: 
  SubmoduleStatusTest.repositoryWithInitializedSubmodule:306 expected:<INITIALIZED> but was:<UNINITIALIZED>
  SubmoduleStatusTest.repositoryWithDifferentRevCheckedOutSubmodule:362 expected:<AnyObjectId[aaaa0000aaaa0000aaaa0000aaaa0000aaaa0000]> but was:<null>
  FileTreeIteratorTest.submoduleWithNoHead:368 expected:<AnyObjectId[0000000000000000000000000000000000000000]> but was:<AnyObjectId[6b584e8ece562ebffc15d38808cd6b98fc3d97ea]>

Tests in error: 
  CloneCommandTest.testCloneRepositoryWithNestedSubmodules:396 » NoHead Commit o...
  CloneCommandTest.testCloneRepositoryWithSubmodules:335 » NoWorkTree Bare Repos...
  CloneCommandTest.testCloneWithAutoSetupRebase:463 » NoWorkTree Bare Repository...
  CloneCommandTest.testCloneRepositoryOnlyOneBranch:246 » NoWorkTree Bare Reposi...
  CloneCommandTest.testCloneRepositoryWithBranch:166 » NoWorkTree Bare Repositor...
  CloneCommandTest.testCloneRepositoryWithTagName:227 » NoWorkTree Bare Reposito...
  CloneCommandTest.testCloneRepository:114 » NoWorkTree Bare Repository has neit...
  CloneCommandTest.testCloneRepositoryWithMultipleHeadBranches:314 » NoWorkTree ...
  CloneCommandTest.testCloneRepositoryWhenDestinationDirectoryExistsAndIsNotEmpty:288 » NoWorkTree
  CommitCommandTest.commitAfterSquashMerge:458 » NullPointer
  CommitCommandTest.commitSubmoduleUpdate:278 » NoWorkTree Bare Repository has n...
  CommitCommandTest.commitNewSubmodule:230 » NoWorkTree Bare Repository has neit...
  GarbageCollectCommandTest.testGConeCommit:72 » NullPointer
  GarbageCollectCommandTest.testGCmoreCommits:86 » NullPointer
  GitConstructionTest.testOpen:111 » RepositoryNotFound repository not found: /U...
  LsRemoteCommandTest.testLsRemoteWithTags:104 » NoWorkTree Bare Repository has ...
  LsRemoteCommandTest.testLsRemoteWithHeads:121 » NoWorkTree Bare Repository has...
  LsRemoteCommandTest.testLsRemote:87 » NoWorkTree Bare Repository has neither a...
  MergeCommandTest.testFastForward:138 » NullPointer
  MergeCommandTest.testMultipleCreationsSameContent:489 » NullPointer
  MergeCommandTest.testAlreadyUpToDate:118 » NullPointer
  MergeCommandTest.testFastForwardNoCommit:160 » NullPointer
  MergeCommandTest.testMergeInItself:99 » NullPointer
  MergeCommandTest.testFastForwardWithFiles:191 » NullPointer
  MergeCommandTest.testMergeSuccessAllStrategies » ParameterizedAssertion testMe...
  RebaseCommandTest.testRebaseShouldIgnoreMergeCommits:288 » NullPointer
  RebaseCommandTest.testFastForwardWithMultipleCommits:192 » NullPointer
  RebaseCommandTest.testDetachedHead:456 » NullPointer
  RebaseCommandTest.testFastForwardWithNewFile:146 » NullPointer
  RebaseCommandTest.testUpToDate:348 » NullPointer
  RebaseCommandTest.testRebaseParentOntoHeadShouldBeUptoDate:330 » NullPointer
  RebaseCommandTest.testConflictFreeWithSingleFile:406 » NullPointer
  ReflogCommandTest.testAmendReflog:136 » NullPointer
  ReflogCommandTest.testBranchReflog:113 » NullPointer
  ReflogCommandTest.testHeadReflog:89 » NullPointer
  ResetCommandTest.testSoftReset:191->assertReflog:495 » NullPointer
  ResetCommandTest.testMixedReset:213->assertReflog:495 » NullPointer
  ResetCommandTest.testHardReset:154->assertReflog:495 » NullPointer
  RevertCommandTest.testRevert:118 » NullPointer
  StashApplyCommandTest.workingDirectoryContentConflict:368 » NullPointer
  StashApplyCommandTest.workingDirectoryEditPreCommit:470 » NullPointer
  StashApplyCommandTest.workingDirectoryContentMerge:428 » NullPointer
  StashApplyCommandTest.workingDirectoryCleanIndexModify:255 » NullPointer
  StashApplyCommandTest.multipleEdits:340 » NullPointer
  StashApplyCommandTest.workingDirectoryModifyInSubfolder:202 » NullPointer
  StashApplyCommandTest.indexContentConflict:448 » NullPointer
  StashApplyCommandTest.stashChangeInANewSubdirectory:502 » NullPointer
  StashApplyCommandTest.indexAdd:124 » NullPointer
  StashApplyCommandTest.workingDirectoryDeleteIndexAdd:284 » NullPointer
  StashApplyCommandTest.workingDirectoryDeleteIndexEdit:311 » NullPointer
  StashApplyCommandTest.workingDirectoryModifyIndexChanged:228 » NullPointer
  StashApplyCommandTest.workingDirectoryDelete:98 » NullPointer
  StashApplyCommandTest.indexDelete:149 » NullPointer
  StashApplyCommandTest.workingDirectoryModify:173 » NullPointer
  StashApplyCommandTest.stashedContentMerge:399 » NullPointer
  StashApplyCommandTest.testApplyStashWithDeletedFile:560 » NullPointer
  StashCreateCommandTest.refLogIncludesCommitMessage:447 » NullPointer
  StashDropCommandTest.dropSingleStashedCommit:125 » NullPointer
  StashDropCommandTest.dropMiddleStashCommit:224 » NullPointer
  StashDropCommandTest.dropFirstStashedCommit:182 » NullPointer
  StashDropCommandTest.dropBoundaryStashedCommits:277 » NullPointer
  StashDropCommandTest.dropWithInvalidLogIndex:107 » NullPointer
  StashListCommandTest.multipleStashedCommits:129 » NullPointer
  StashListCommandTest.emptyStashReflog:85 » NullPointer
  StashListCommandTest.singleStashedCommit:102 » NullPointer
  GCTest.testPackRepoWithCorruptReflog:451 » NullPointer
  GCTest.testNotPackTwice:566 » NullPointer
  GCTest.testKeepFiles:462 » NullPointer
  GCTest.concurrentRepack:287 » Execution java.lang.NullPointerException
  GCTest.testPackCommitsAndLooseOneWithPruneNow:616 » NullPointer
  GCTest.testPackAllObjectsInOnePack:426 » NullPointer
  GCTest.testIndexSavesObjects:658 » NullPointer
  GCTest.testPruneNone:700 » NullPointer
  GCTest.testPackCommitsAndLooseOneWithPruneNowNoReflog:641 » NullPointer
  GCTest.testPackCommitsAndLooseOne:540 » NullPointer
  GCTest.testPack2Commits:523 » NullPointer
  GCTest.testPackCommitsAndLooseOneNoReflog:596 » NullPointer
  GCTest.testIndexSavesObjectsWithPruneNow:676 » NullPointer
  ReflogReaderTest.testCheckout:225 » NullPointer
  ReflogReaderTest.testReadRightLog:189 » NullPointer
  ReflogReaderTest.testReadWhileAppendIsInProgress:163 » NullPointer
  ReflogReaderTest.testNoLog:218 » NullPointer
  ReflogReaderTest.testReadLineWithMissingComment:201 » NullPointer
  ReflogReaderTest.testSpecificEntryNumber:240 » NullPointer
  ReflogReaderTest.testReadOneLine:101 » NullPointer
  ReflogReaderTest.testReadTwoLine:128 » NullPointer
  RefUpdateTest.testNewNamespaceConflictWithPackedPrefixNameExists:164 » NullPointer
  RefUpdateTest.testNoCacheObjectIdSubclass:127 » NullPointer
  RefUpdateTest.testRenameBranchHasPreviousLog:648 » NullPointer
  RefUpdateTest.testRenameCurrentBranch:672 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisOtherLockFrom:806->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisToLockTo:799->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testRenameRefNameColission2avoided:874 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisToLockFrom:792->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisFromLockTo:785->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testDeleteHEADreferencedRef:213 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisFromLockFrom:778->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisFromLockHEAD:771->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testUpdateRefDetached:357 » NullPointer
  RefUpdateTest.testNewNamespaceConflictWithLoosePrefixOfExisting:179 » NullPointer
  RefUpdateTest.testRenameBranchAlsoInPack:701 » NullPointer
  RefUpdateTest.testDeleteHead:231 » NullPointer
  RefUpdateTest.testRenameBranchCannotLockAFileHEADisOtherLockTo:813->tryRenameWhenLocked:723 » NullPointer
  RefUpdateTest.testNewNamespaceConflictWithPackedPrefixOfExisting:192 » NullPointer
  RefUpdateTest.testRenameBranchNoPreviousLog:626 » NullPointer
  RefUpdateTest.testNewNamespaceConflictWithLoosePrefixNameExists:152 » NullPointer
  RefUpdateTest.testRenameRefNameColission1avoided:838 » NullPointer
  RefUpdateTest.testUpdateRefDetachedUnbornHead:387 » NullPointer
  ReflogConfigTest.testlogAllRefUpdates:66 » NullPointer
  ReflogResolveTest.resolveUnnamedCurrentBranchCommits:85 » NullPointer
  ReflogResolveTest.resolvePreviousBranch:146 » NullPointer
  ReflogResolveTest.resolveMasterCommits:71 » NullPointer
  ReflogResolveTest.resolveReflogParent:117 » NullPointer
  SubmoduleAddTest.addSubmoduleWithExistingSubmoduleDefined:251 » NoWorkTree Bar...
  SubmoduleAddTest.addSubmodule:133 » NoWorkTree Bare Repository has neither a w...
  SubmoduleAddTest.addSubmoduleWithRelativeUri:195 » NoWorkTree Bare Repository ...
  SubmoduleSyncTest.repositoryWithSubmodule:116 » NoWorkTree Bare Repository has...
  SubmoduleSyncTest.repositoryWithRelativeUriSubmodule:187 » NoWorkTree Bare Rep...
  SubmoduleUpdateTest.repositoryWithSubmodule:116 » NoWorkTree Bare Repository h...
  FileTreeIteratorTest.submoduleNestedWithHeadMatchingIndex:423 » NoWorkTree Bar...
  FileTreeIteratorTest.submoduleHeadMatchesIndex:289 » NoWorkTree Bare Repositor...
  FileTreeIteratorTest.submoduleDirectoryIterator:389 » NoWorkTree Bare Reposito...

Tests run: 2553, Failures: 3, Errors: 122, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JGit - Parent ...................................... SUCCESS [  1.761 s]
[INFO] JGit - Core ........................................ SUCCESS [ 18.694 s]
[INFO] JGit - Ant Tasks ................................... SUCCESS [  3.065 s]
[INFO] JGit Archive Formats ............................... SUCCESS [  1.736 s]
[INFO] JGit - AWT User Interface .......................... SUCCESS [  2.233 s]
[INFO] JGit - HTTP Server ................................. SUCCESS [  2.273 s]
[INFO] JGit - Core Java7 Support .......................... SUCCESS [  1.661 s]
[INFO] JGit - Console User Interface ...................... SUCCESS [  1.488 s]
[INFO] JGit - Command Line Interface ...................... SUCCESS [  5.283 s]
[INFO] JGit - JUnit Utility Classes ....................... SUCCESS [  1.863 s]
[INFO] JGit - JUnit Http Utility Classes .................. SUCCESS [  1.708 s]
[INFO] JGit - Core Tests .................................. FAILURE [02:58 min]
[INFO] JGit - Ant Tasks Tests ............................. SKIPPED
[INFO] JGit - HTTP Tests .................................. SKIPPED
[INFO] JGit - Command Line Interface Tests ................ SKIPPED
[INFO] JGit - Core Java 7 Tests ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:40 min
[INFO] Finished at: 2015-05-11T15:08:45-04:00
[INFO] Final Memory: 38M/546M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project org.eclipse.jgit.test: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/joe/workspace/jgit/org.eclipse.jgit.test/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project org.eclipse.jgit.test: There are test failures.
```

**Comment by joewiz** [comment]
Even when skipping the tests with `mvn install -DskipTests`, I get this error:

```
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/DefaultUploadPackFactoryTest.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/DefaultUploadPackFactoryTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/FileResolverTest.java:[86,54] no suitable constructor found for FileResolver(java.io.File,boolean)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS,java.io.File,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/FileResolverTest.java:[106,28] no suitable constructor found for FileResolver(java.io.File,boolean)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS,java.io.File,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/FileResolverTest.java:[117,28] no suitable constructor found for FileResolver(java.io.File,boolean)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS,java.io.File,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/FileResolverTest.java:[128,28] no suitable constructor found for FileResolver(java.io.File,boolean)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS,java.io.File,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/joe/workspace/jgit/org.eclipse.jgit.http.test/tst/org/eclipse/jgit/http/test/FileResolverTest.java:[145,61] no suitable constructor found for FileResolver(java.io.File,boolean)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS,java.io.File,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.eclipse.jgit.transport.resolver.FileResolver.FileResolver(org.eclipse.jgit.util.FS) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JGit - Parent ...................................... SUCCESS [  1.703 s]
[INFO] JGit - Core ........................................ SUCCESS [ 17.975 s]
[INFO] JGit - Ant Tasks ................................... SUCCESS [  1.543 s]
[INFO] JGit Archive Formats ............................... SUCCESS [  2.152 s]
[INFO] JGit - AWT User Interface .......................... SUCCESS [  2.631 s]
[INFO] JGit - HTTP Server ................................. SUCCESS [  1.959 s]
[INFO] JGit - Core Java7 Support .......................... SUCCESS [  1.560 s]
[INFO] JGit - Console User Interface ...................... SUCCESS [  1.348 s]
[INFO] JGit - Command Line Interface ...................... SUCCESS [  3.798 s]
[INFO] JGit - JUnit Utility Classes ....................... SUCCESS [  3.245 s]
[INFO] JGit - JUnit Http Utility Classes .................. SUCCESS [  1.516 s]
[INFO] JGit - Core Tests .................................. SUCCESS [  0.448 s]
[INFO] JGit - Ant Tasks Tests ............................. SUCCESS [  0.108 s]
[INFO] JGit - HTTP Tests .................................. FAILURE [  0.181 s]
[INFO] JGit - Command Line Interface Tests ................ SKIPPED
[INFO] JGit - Core Java 7 Tests ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.434 s
[INFO] Finished at: 2015-05-11T15:12:28-04:00
[INFO] Final Memory: 44M/544M
[INFO] ------------------------------------------------------------------------
```

**Comment by shabanovd** [comment]
@joewiz publish xar here https://github.com/shabanovd/eXgit/releases/tag/v0.3

**Comment by shabanovd** [comment]
also you may use `-Dmaven.test.skip=true` or `-DskipTests` parameter for `maven install`

**Comment by joewiz** [comment]
Thanks, @shabanovd!  I downloaded and successfully installed it.  I'd still like to be able to build this on my local system.  Do you think it's possible to describe the build steps so I and others can build?  I'm happy to help with documentation - as you know!

**Comment by mcmeeking** [comment]
Just FYI for anyone who stumbles across this:

To build successfully, in `pom.xml` replace `http://download.eclipse.org/jgit/maven` with `http://archive.eclipse.org/jgit/maven/`
